export const groupDetail = {
  GET_GROUP_DETAIL: 'GET_GROUP_DETAIL',
  GET_MEMBERS: 'GET_MEMBERS',
  SHOW_MORE: 'SHOW_MORE',
  IS_LAST: 'IS_LAST',
  CREATE_MEMBER: 'CREATE_MEMBER',
  GET_MEMBER_NOT_IN_GROUP: 'GET MEMBER NOT IN GROUP',
  GET_POSITION: 'GET POSITION',
};
